version: '2'
services:
  redorgreenapi:
    image: cdaringe/redorgreenapi
    environment:
      NODE_ENV: production
      DB_HOST: redorgreendb
      DB_PORT: 5984
      VIRTUAL_PORT: 8081
      VIRTUAL_HOST: redorgreen.$HOSTNAME,www.redorgreen.$HOSTNAME
      CERT_NAME: server
    ports:
      - '8081:8081'
    depends_on:
      - redorgreendb
    restart: unless-stopped
    network_mode: bridge
    links:
      - redorgreendb # https://docs.docker.com/compose/networking/#links
  redorgreendb:
    image: couchdb:1.6.1
    restart: unless-stopped
    network_mode: bridge # https://github.com/jwilder/nginx-proxy/issues/622
    volumes:
      - '/www/redorgreen/couchdb:/usr/local/var/lib/couchdb'
