version: '2'
services:
  # senor-salsa-api:
  #   image: cdaringe/redorgreen
  #   environment:
  #     NODE_ENV: production
  #     DB_HOST: redorgreendb
  #     DB_PORT: 5984
  #   expose:
  #     - 5984
  #   depends_on:
  #     - redorgreendb
  #   restart: unless-stopped
  redorgreendb:
    image: couchdb:1.6.1
    ports:
      - '5984:5984' # drop in prd!
    volumes:
      - '/www/redorgreen/couchdb:/var/lib/couchdb'
    restart: unless-stopped
